version: '3.1'

services:
  db:
    image: postgres:alpine
    hostname: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_USER=postgressu
      - POSTGRES_DB=documentservice
    networks:
      - mynet

  api:
    container_name: document-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./.env.docker
    environment:
      - DATABASE_URL=postgres://postgressu:postgrespwd@db:5432/documentservice
    restart: on-failure
    networks:
      - mynet

networks:
  mynet:
    name: my-shared-db-network

